### ISSUE TITLE
Document minimum version of Java required and changes to that minimum

### ISSUE THREAD

**Issue by tfmorris** [revelc/impsort-maven-plugin#106]
**Is your feature request related to a problem? Please describe.**
I can't find any place that the minimum Java version is documented and a couple of months ago Java 11 support was dropped without, as far as I can tell, any notice.

https://github.com/revelc/impsort-maven-plugin/commit/8f376a75f92b284a31f121949ff2ad3e26b9cdea

**Describe the solution you'd like**
It would be useful to have the minimum version of Java documented and to include in the release notes a note when that changes.

**Comment by hazendaz** [comment]
Hi, the data is in milestones.  I'm working with @ctubbsii to make sure we try to at least use releases or legacy changelog so its obviously as I'm sure no one would look at milestones.  The current release even requires java 17 now.

**Comment by hazendaz** [comment]
support on latest works through java 21 as well.

**Comment by ctubbsii** [comment]
You can always look at the project's POM file to determine the minimum supported Java version, as it's a hard-coded property that follows maven conventions: `maven.compiler.release` is the property name to look for. For any Maven project, you can look for that property, or `maven.compiler.target`, or you can look for the target or release properties in the `maven-compiler-plugin` configuration. This isn't specific to this project, but a general Maven convention that you can look for in any Maven project.

But yes, we can start doing release notes in GitHub for some stuff. I'm not sure this particular issue would have even been noted, though. First, because I don't think it was an explicit decision, but just incidental. And second, because of the note I made above about the target Java version being specified in a well-known location by convention. I would say that, in general, you can expect any new version of any plugin coming from this group to drop support for end-of-life Java versions without much fanfare (because Java's end-of-life fanfare is usually loud enough). However, we're always going to make it at least a minor version bump when that happens... unless there's extreme circumstances, we're not going to change the minimum JDK version on a bugfix/patch release (for example, going from 1.4.1 to 1.4.2).

I actually checked just now and it looks like the plugin still compiles to 11, so we're not even using any 17-specific stuff (yet). So, if you need it to work for JDK 11, but can probably rebuild from source as a workaround.

I'll mark this issue for the next release milestone, so we remember to add it to the release notes, to use as a template for future releases.

**Comment by hazendaz** [comment]
I added releases back to main page and added entries for each time java version changed as well as indicated the latest 1.12.0 should fully support java 21 so it stands out.  Closing as completed.
