### ISSUE TITLE
Java 8 and Maven 3.9 will make the plugin fail

### ISSUE THREAD

**Issue by JojoIce** [revelc/impsort-maven-plugin#110]
**Describe the bug**
Using Java 8 seems to restrict to v 1.6.2. Using maven 3.9+ to trigger the plugin will make the plugin fail.
The problem and to some extent the solution is quite well explained here: https://stackoverflow.com/questions/75652635/a-required-class-was-missing-while-executing-maven-plugin-with-github-action
and further here:
https://github.com/actions/runner-images/issues/7216

**Versions (OS, Maven, Java, and others, as appropriate):**
 - <=1.6.2
 - Java 8
 - Maven 3.9+

**To Reproduce**
Setup environment with the versions as above and a project with impsort and trigger the plugin.

**Expected behavior**
Impsort should execute without failing, but fails in this configuration.
This seems to be fixed in later version of impsort, but that is not available for java 8, so just applying the fix for a 1.6.3 would allow people stuck at java 8 to still use impsort.

SO comment:
"If you are a plugin author then good to stop using plexus-utils FileUtils and add maven-shared-utils as an explicit dependency in the plugin pom.xml. maven-shared-utils has a drop-in replacement for FileUtils.getFiles for example."

Not sure if that is the fix, or upgrading the plexus-utils to a later version.

**Screenshots**
See the stackoverflow link above

**Additional context**

**Comment by hazendaz** [comment]
I'm not sure we will release a patch to java 8 as that is pretty old.  Maven 3.9 is a stepping stone to 4.0.  Therefore, I think if stuck, it would make more sense to stay on maven 3.8 since attempting to get closer to 4 would be a lost cause for a java 8 user not using newer build version.  While unlikely maven makes more 3.8 patches it's technically still supported.

It is also well documented that java 8 is not required to build to java 8.  A lot of plugins and even libraries have dropped support now.  In fact it would be better all around to use newer jvm for other benefits and cross compile with release flags and enforcer rules for binary protections to benefit from latest tools.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Joakim Johnsson ***@***.***>
Sent: Monday, September 2, 2024 5:37:46 AM
To: revelc/impsort-maven-plugin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [revelc/impsort-maven-plugin] Java 8 and Maven 3.9 will make the plugin fail (Issue #110)


Describe the bug
Using Java 8 seems to restrict to v 1.6.2. Using maven 3.9+ to trigger the plugin will make the plugin fail.
The problem and to some extent the solution is quite well explained here: https://stackoverflow.com/questions/75652635/a-required-class-was-missing-while-executing-maven-plugin-with-github-action
and further here:
actions/runner-images#7216<https://github.com/actions/runner-images/issues/7216>

Versions (OS, Maven, Java, and others, as appropriate):

  *   <=1.6.2
  *   Java 8
  *   Maven 3.9+

To Reproduce
Setup environment with the versions as above and a project with impsort and trigger the plugin.

Expected behavior
Impsort should execute without failing, but fails in this configuration.
This seems to be fixed in later version of impsort, but that is not available for java 8, so just applying the fix for a 1.6.3 would allow people stuck at java 8 to still use impsort.

SO comment:
"If you are a plugin author then good to stop using plexus-utils FileUtils and add maven-shared-utils as an explicit dependency in the plugin pom.xml. maven-shared-utils has a drop-in replacement for FileUtils.getFiles for example."

Not sure if that is the fix, or upgrading the plexus-utils to a later version.

Screenshots
See the stackoverflow link above

Additional context

**Comment by hazendaz** [comment]
The stack overflow is correct in how to address.  That applies to any plugin with same issue.
