### ISSUE TITLE
mixing static imports of inner classes into other static imports (within same group)

### ISSUE THREAD

**Issue by leubedane** [revelc/impsort-maven-plugin#14]
We noticed that the impsort-maven-plugin sorts static imports differently to eclipse (or IntellijIdea with eclipseFormatter plugin) in certain cases.

While Eclipse and Intellij keep static imports per Type together, the plugin mixes static imports from a top-level class with those of an inner class.

Example:
Top-level class: A with constants BAR and FOO
Inner class A.C with constants EPSILON and OMEGA
```java
public static class A {
  public static final String BAR = "bar";
  public static final String FOO = "foo";

  public static class C {
    public static final String EPSILON = "epsilon";
    public static final String OMEGA = "omega";
  }
}

```

Sorted static imports per eclipse:
```java
import static com.foo.bar.A.BAR;
import static com.foo.bar.A.FOO;
import static com.foo.bar.A.C.EPSILON;
import static com.foo.bar.A.C.OMEGA;
```

Sorted static imports per plugin:
```java
import static com.foo.bar.A.BAR;
import static com.foo.bar.A.C.EPSILON;
import static com.foo.bar.A.C.OMEGA;
import static com.foo.bar.A.FOO;
```

Is there any workaround we missed?
Best regards
Dane

**Comment by ctubbsii** [comment]
Interesting. This plugin just does a simple lexicographical ordering. It has no knowledge of classes at all. For static imports, it may be possible to use a custom comparator that sorts on all but the last element, and then on the last element only if necessary.

I'm trying to think if there's any edge cases in the non-static case, but I think it already does what we'd expect. Example:

```java
public static class A {
  public static class B {}
  public static class C {
    public class E {}
    public class F {}
  }
  public static class D {}
}
```

This should result in:

```java
import A;
import A.B;
import A.C;
import A.C.E;
import A.C.F;
import A.D;
```

So, I think we just need a slightly smarter comparator for the static imports that can compare the containing class first. Feel free to offer a pull request, or I can work on it later this week. It should be a very tiny change.

**Comment by ctubbsii** [comment]
Looking at this further, I realize that basically, static imports should be using a breadth-first ordering, and non-static should be using a depth-first ordering. It is a little weird that this is the case, and I'm wondering if there's an additional edge case in the non-static scenario. Should it, in fact, be the following?

```java
import A;
import A.B;
import A.C;
import A.D;
import A.C.E;
import A.C.F;
```

This is a bit weird, because the the inner-class `A.C` is separated from its own inner-classes in order to be grouped with its siblings at the same depth. You don't see this with the static case, because you can't import the thing that defines your hierarchy (Classes and Interfaces) there.

I have a pull request coming shortly to add a choice between breadth-first and depth-first sorting for static imports, but now I'm wondering if I should have a knob for the non-static imports also. Please let me know what you think either here or on the pull request.

**Comment by AlainLatscha** [comment]
The alphanumeric sorting makes more sense to me.The problem is that it doesn't match with the Eclipse behaviour (or IntelliJ with Eclipse Formatter plugin). I did the test and the non static imports are sorted by Eclipse as follows:
```
import A;
import A.B;
import A.C;
import A.C.E;
import A.C.F;
import A.D;
```
Your commit makes sense to me.
When will there be a release of it?

**Comment by ctubbsii** [comment]
I can release today, after I test #15 and merge it in.

**Comment by ctubbsii** [comment]
Version 1.3.0 has been released. It might take a few hours to sync to Maven Central.

**Comment by AlainLatscha** [comment]
It works very fine. Thanks.
