### ISSUE TITLE
allow avoiding empty line between groups

### ISSUE THREAD

**Issue by Ladicek** [revelc/impsort-maven-plugin#28]
I'd like to configure import order that matches what IntelliJ IDEA does (in its default configuration). That is:

```
import "all other imports"
<blank line>
import javax.*
import java.*
<blank line>
import static "all other imports"
```

I got very close by using this configuration:

```xml
<configuration>
    <groups>*,javax.,java.</groups>
    <staticGroups>*</staticGroups>
    <staticAfter>true</staticAfter>
    <removeUnused>true</removeUnused>
</configuration>
```

However, this creates an empty line between the `javax.` and `java.` groups. One last thing to avoid! :-)

The configuration might just use a different separator to mean "two different groups, but no empty line". Something like `*,javax.+java.`.

WDYT? I can try implementing this, if you think it's worth it.

**Comment by ctubbsii** [comment]
This issue seems similar to #22 

This should work already if you use:

```xml
<configuration>
    <groups>*,java</groups>
    <staticGroups>*</staticGroups>
    <staticAfter>true</staticAfter>
    <removeUnused>true</removeUnused>
</configuration>
```

Of course, this could pick up other patterns like `javacc.` and `javatar.`, but I think those are rare enough to not really matter much.

Personally, I don't think it makes much sense to add the concept of a "group" that isn't separated by a blank line, since a group, by definition, is a cluster of imports that are grouped together, separated by blank lines.

Furthermore, as stated on #22 , it is a non-goal to try to mimic the import ordering of any particular IDE. Rather, the whole point of the plugin is to allow projects to standardize on import ordering during a Maven build, using reasonable and simple syntax, *regardless* of what IDE one uses for editing the project.

That said, I will consider a syntax for allowing groups to be defined with more complex matching patterns to create sub-groups that are not whitespace separated, such as `<groups>java.|javax.,com.mycompany.,*</groups>`.

**Comment by Ladicek** [comment]
`<groups>*,java</groups>` won't sort `javax.` stuff before `java.` stuff, so it's not exactly what I'm after :-)

I appreciate you don't want to mimic everything IDEs [can] do, and I'm quite happy with what I've got now, so feel free to disregard this.

Thanks for the nice plugin!
