### ISSUE TITLE
externalizing funcionality

### ISSUE THREAD

**Issue by Loki-Afro** [revelc/impsort-maven-plugin#39]
**Is your feature request related to a problem? Please describe.**
I want to use the import clean up functionality most of all as a library, not as a maven plugin.

**Describe the solution you'd like**
Separating the "real" code from the actual maven plugin

I know its quite annoying to have 2 projects to maintain, but i couldn't find any project that does the same job and working is working with recent code.

If you consider doing this, {{ImpSort}} should have a String as input, i had to work around this by creating temp files ...

**Comment by ctubbsii** [comment]
I did try to write the code so that you can use it this way. I put the Maven stuff in the `net.revelc.code.impsort.maven.plugin` package, but the main library code is two packages above that in `net.revelc.code.impsort`. The entry point is the `ImpSort` class. Granted, there's not a lot of javadocs to use it this way, but it was always my intent that somebody could do that if they wanted to.  You can look at the maven plugin Mojo classes to see how it is used.

If you try it, let me know how it goes!

But I'm closing this. If you run into a problem using it (such as a hard dependency on Maven stuff in the main package) feel free to open a ticket.
