### ISSUE TITLE
Implement support for a cache file similar to formatter-maven-cache.properties for impsort 

### ISSUE THREAD

**Issue by Elisedlund-ericsson** [revelc/impsort-maven-plugin#41]
We waste a lot of time on impsort as it runs on all our files everytime even if  files that hasn't really changed since last impsort. 

on your other project: https://github.com/revelc/formatter-maven-plugin you have a cache that stores the hash of the file and then it does not attempt to format the file a second time if it has the same hash (and therefore unchanged) 

By including the formatter-maven-cache.properties in our git repo and use the cachedir:
https://code.revelc.net/formatter-maven-plugin/format-mojo.html#cachedir
we save a lot of wasted time.  ( 20s )

impsort:sort takes roughly the same amount of time as formatter:format (before cache file)

Could a similar cache with hashes be implemented for impsort:sort I would imagine that it would save us ~20s more.  

(Bonus points if it would have the same format as formatter-maven-cache.properties as always run  impsort:sort and formatter:format together, so we would probably use the same cache file for both)

**Comment by ctubbsii** [comment]
I'm not opposed to adding a cache, but I'm not sure what advantage would be added to have it use the same format. Whether the same format or not, you wouldn't be able to use the same file. If you did, you would see entries added by the formatter-maven-plugin, and those files with entries in the cache would be skipped, even though they have not been processed yet by this plugin. We can make the configuration the same or similar, because that part is easy, but the file would have to be a different file. As for the format, I think I would prefer BSD-style checksum formats:

```
ALGORITHM (FILENAME) = CHECKSUM
```

However, I would have to check to see what the formatter-maven-plugin is doing first.

**Comment by Elisedlund-ericsson** [comment]
> Whether the same format or not, you wouldn't be able to use the same file. If you did, you would see entries added by the formatter-maven-plugin, and those files with entries in the cache would be skipped, even though they have not been processed yet by this plugin.

True, 
I guess it would be possible to workaround this issue by only letting formatter-maven-plugin read the cache file but not write to it. basically making our flow,  
"read formatter-maven-cache.properties" -> do formatter:format + impsort:sort -> "write formatter-maven-cache.properties"
However it feels like to much of a hack, we would be fine with two separate files as I think we would get 90%+ of all the benefits from just that.
