### ISSUE TITLE
[Feature] Make includes work with `src/generated`

### ISSUE THREAD

**Issue by agreedSkiing** [revelc/impsort-maven-plugin#68]
**Is your feature request related to a problem? Please describe.**
Just this morning I tried to us the maven plugin to format our `src/generated/java` code but noticed that it was completely skipped when running the maven plugin.

For our project we check in the `src/generated/java` folder and all of the code inside of it since it generated from an openAPI specification and want to remove all unused imports that the openAPI generate creates.

**Describe the solution you'd like**
Make it possible to add `src/generated/java` as a valid path

**Describe alternatives you've considered**
_None_

**Additional context**
_None_

**Comment by hazendaz** [comment]
It's technically bad to check that code in.  There is no reason to do so.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Erik Åsén ***@***.***>
Sent: Friday, January 27, 2023 7:30:14 AM
To: revelc/impsort-maven-plugin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [revelc/impsort-maven-plugin] [Feature] Make includes work with `src/generated` (Issue #68)


Is your feature request related to a problem? Please describe.
Just this morning I tried to us the maven plugin to format our src/generated/java code but noticed that it was completely skipped when running the maven plugin.

For our project we check in the src/generated/java folder and all of the code inside of it since it generated from an openAPI specification and want to remove all unused imports that the openAPI generate creates.

Describe the solution you'd like
Make it possible to add src/generated/java as a valid path

Describe alternatives you've considered
None

Additional context
None

**Comment by agreedSkiing** [comment]
What I tried was this
```xml
            <plugin>
                <groupId>net.revelc.code</groupId>
                <artifactId>impsort-maven-plugin</artifactId>
                <version>1.8.0</version>
                <configuration>
                    <includes>
                        <include>**/generated/**/*.java</include>
                    </includes>
                </configuration>
                <executions>
                    <execution>
                        <id>sort-imports</id>
                        <goals>
                            <goal>sort</goal>
                            <!-- runs at process-sources phase by default -->
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
```xml
            <plugin>
                <groupId>net.revelc.code</groupId>
                <artifactId>impsort-maven-plugin</artifactId>
                <version>1.8.0</version>
                <configuration>
                    <includes>
                        <include>src/generated/**</include>
                    </includes>
                </configuration>
                <executions>
                    <execution>
                        <id>sort-imports</id>
                        <goals>
                            <goal>sort</goal>
                            <!-- runs at process-sources phase by default -->
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

and it just gives me 
```bash
$ mvn impsort:sort
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------------< org.acme:project >-----------------------------
[INFO] Building project 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- impsort-maven-plugin:1.8.0:sort (default-cli) @ project  ---
[INFO] Processed 0 files in 00:00.009 (Already Sorted: 0, Needed Sorting: 0)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.382 s
[INFO] Finished at: 2023-02-02T16:45:04+01:00
[INFO] ------------------------------------------------------------------------
```

and then last run
```xml
            <plugin>
                <groupId>net.revelc.code</groupId>
                <artifactId>impsort-maven-plugin</artifactId>
                <version>1.8.0</version>
                <configuration>
                    <includes>
                        <include>**/*.*</include>
                    </includes>
                </configuration>
                <executions>
                    <execution>
                        <id>sort-imports</id>
                        <goals>
                            <goal>sort</goal>
                            <!-- runs at process-sources phase by default -->
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
with maven --debug this time
[maven.log](https://github.com/revelc/impsort-maven-plugin/files/10570748/maven.log)

**Comment by ctubbsii** [comment]
There is also a `testSourceDirectory` and a `sourceDirectory`. It looks like includes/excludes are relative to those. You could try setting `sourceDirectory` to `.` and then includes to `src/main/java/**/*.java` and `src/generated/**/*.java`.

**Comment by agreedSkiing** [comment]
That did the trick and maybe it should be documented? I think this trick was also needed needed to format only one file in formatter-maven-plugin if a full path was given to the plugin.

```log
[DEBUG] Reading file /home/eriase/repos/org-acme-backend/src/generated/java/org/acme/project/addressbook/endpoint/dto/CodeWrapperCodingDto.java
```

```xml
<plugin>
                <groupId>net.revelc.code</groupId>
                <artifactId>impsort-maven-plugin</artifactId>
                <version>1.8.0</version>
                <configuration>
                    <includes>
                        <include>**/generated/**/*.java</include>
                    </includes>
                    <sourceDirectory>.</sourceDirectory>
                </configuration>
                <executions>
                    <execution>
                        <id>sort-imports</id>
                        <goals>
                            <goal>sort</goal>
                            <!-- runs at process-sources phase by default -->
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

**Comment by ctubbsii** [comment]
The directory where it executes, and from which includes/excludes are relative, [is documented already and configurable](https://code.revelc.net/impsort-maven-plugin/check-mojo.html#directories). The configuration I suggested was internal, apparently. The correct way to override the directories is to use the `<directories/>` option, rather than override the internal `sourceDirectory` or `testSourceDirectory` code... I only found those by looking at the debug output, rather than the documentation, but it does look like this is already an available feature and documented. So, I don't think there's anything further to do here.
