### ISSUE TITLE
Manage star imports

### ISSUE THREAD

**Issue by delanym** [revelc/impsort-maven-plugin#70]
An issue about detecting star imports was closed because it was unnecessarily duplicating functionality already available in the checkstyle project https://github.com/revelc/impsort-maven-plugin/issues/21

But checkstyle only complains about violations, it doesn't fix anything. With a codebase where star is already in use I would have to go and manually convert all the uses to single imports. What I am proposing is for this plugin to do that work. Just like the formatter-maven-plugin, it should ensure that the code follows a convention with respect to imports.

Intellij's configuration allows specifying a `Class count to use import with '*'` and a `Names count to use static import with '*'`
So perhaps the way to do this is define 2 parameters,  `classCount` and `namesCount`.
When the count is set to 0, star imports are ignored. When the count is greater than zero, a star import is expanded if the number of resulting imports is less than the count.
Sound reasonable?

**Comment by ctubbsii** [comment]
It's not possible for us to fix anything with this plugin, because it doesn't try to compile anything, and knows nothing about the class path, or even the concept of classes. So it has no way to do any kind of expansion. All it can do is organize the parsed tokens from the Java source file. That's it.

I do not think it's worth adding in any of that complexity, and making this plugin more heavyweight, when the user's IDE is much more appropriate for doing this kind of work, once checkstyle has flagged it for them.

So, unless you know if a solution that operates on source-only, does not require project compilation, and keeps this plugin lightweight, I think it's best we consider this one out of scope for this plugin. Closing for now... but if you actually do have a solution that meets that criteria, I'm happy to re-open this.

**Comment by delanym** [comment]
@ctubbsii I see. Is it a possibility to add this to formatter-maven-plugin?

**Comment by hazendaz** [comment]
Use open rewrite maven plugin.  In fact it's done in their impsort which makes this plugin then redundant.  I've tested it works as expected.

Even spotless maven plugin I'd having discussion.  Same issues as to why not done as here but also part of their import sorting which one can reject builds at least on using it either by zapping them with maven or throughing exception with groovy.

Speaking on spotless, it basically makes all individual formatters redundant.

Do I think this should be here, yes.



Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hazendaz** [comment]
On open rewrite.  Only need their remove unused imports is all that is needed so you can still use this plugin as well.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hazendaz** [comment]
@delanym 

Here is how to do with rewrite-maven-plugin.

```
 <plugin>
            <groupId>org.openrewrite.maven</groupId>
            <artifactId>rewrite-maven-plugin</artifactId>
            <version>4.45.0</version>
              <configuration>
                <activeRecipes>
                  <recipe>org.openrewrite.java.RemoveUnusedImports</recipe>
                </activeRecipes>
              </configuration>
              <executions>
              <execution>
                <phase>process-sources</phase>
                <goals>
                  <goal>run</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
```

**Comment by delanym** [comment]
Thanks @hazendaz but I've been unable to use that plugin for a while now

https://github.com/openrewrite/rewrite-maven-plugin/issues/133
https://github.com/openrewrite/rewrite-maven-plugin/issues/540

It would probably only make sense if I was processing multiple recipes given the overhead. So my gut still thinks this sort of thing is best done as part of javac, ala Errorprone.
