### ISSUE TITLE
M2E configurator

### ISSUE THREAD

**Issue by wetneb** [revelc/impsort-maven-plugin#77]
**Is your feature request related to a problem? Please describe.**

It would be great if Eclipse could automatically detect the presence of this plugin when importing a Maven project that uses it. It would then import the plugin settings to configure the desired import order in the Eclipse project. This would mean that when I use the "organize imports" functionality in Eclipse, it would follow the import order configured in the Maven plugin.

**Describe the solution you'd like**

We could have a M2E connector similar to https://github.com/revelc/formatter-m2e-configurator. Or perhaps that existing code base could serve as M2E configurator for both Maven plugins?

**Describe alternatives you've considered**

I am not aware of any other mechanism for auto-discovery of such settings.

**Comment by ctubbsii** [comment]
The purpose of this plugin was to be independent of any particular IDE. If somebody wants to pursue an m2e configurator, that's fine, but it's not within scope of this project. If somebody decides to pursue that, I will be willing to accept change proposals that make it easier to support that, if necessary, but I don't want this plugin to depend on Eclipse in any way. They should not be tightly coupled. Also, the configuration for this plugin is very different than Eclipse's import order configuration. It might be difficult to convert from one format to another.

For reference, the m2e configurator, formatter-m2e-configurator is stagnant and not very actively maintained, so it's not a great thing to model after.

Also, it may not be necessary to use an m2e configurator. There was a separate proposal in #75 to just run this in Eclipse, rather than bother integrating with a configurator. That may be sufficient, but there is some outstanding questions on that PR.

**Comment by wetneb** [comment]
That makes total sense, let's close this.
